-- Expand chk_application_state to include all state_id values used across all 30 service packs.
-- Previous constraint was missing states added by newer service packs:
--   PENDING_AT_ASSISTANT_ESTATE_OFFICER, PENDING_AT_CD_ISSUANCE,
--   PENDING_AT_COMPETENT_AUTHORITY, PENDING_AT_ESTATE_OFFICER,
--   PENDING_AT_SDO_PH, PENDING_AT_SENIOR_ASSISTANT (was SR_ASSISTANT),
--   PENDING_AT_SUPERINTENDENT, PENDING_AT_VERIFICATION_OFFICER

ALTER TABLE application DROP CONSTRAINT IF EXISTS chk_application_state;

ALTER TABLE application ADD CONSTRAINT chk_application_state CHECK (
  state_id IN (
    'DRAFT',
    'SUBMITTED',
    'PENDING_AT_CLERK',
    'PENDING_AT_SENIOR_ASSISTANT',
    'PENDING_AT_SR_ASSISTANT_ACCOUNTS',
    'PENDING_AT_ACCOUNT_OFFICER',
    'PENDING_AT_JUNIOR_ENGINEER',
    'PENDING_AT_SDO',
    'PENDING_AT_SDO_PH',
    'PENDING_AT_DRAFTSMAN',
    'PENDING_AT_ESTATE_OFFICER',
    'PENDING_AT_ASSISTANT_ESTATE_OFFICER',
    'PENDING_AT_SUPERINTENDENT',
    'PENDING_AT_VERIFICATION_OFFICER',
    'PENDING_AT_COMPETENT_AUTHORITY',
    'PENDING_AT_CD_ISSUANCE',
    'QUERY_PENDING',
    'RESUBMITTED',
    'APPROVED',
    'REJECTED',
    'CLOSED'
  )
);
