-- Migration 055: Seed court-ready report templates
-- Three standard templates for court documentation workflow

-- 1. Case Summary Report — structured intelligence summary for court submission
INSERT INTO report_template (name, template_type, content_jsonb, content_schema, is_active)
VALUES (
  'Case Summary Report',
  'COURT_EXPORT',
  '{
    "header": { "title": "Case Summary Report", "subtitle": "Social Media Intelligence — Court Submission" },
    "sections": [
      { "type": "keyValue", "title": "Case Information", "entries": [
        { "label": "Case Number", "value": "{{case_number}}" },
        { "label": "Case Title", "value": "{{case_title}}" },
        { "label": "Investigating Officer", "value": "{{officer_name}}" },
        { "label": "Report Date", "value": "{{report_date}}" },
        { "label": "District/Unit", "value": "{{district}}" }
      ]},
      { "type": "text", "title": "Executive Summary", "content": "{{executive_summary}}" },
      { "type": "table", "title": "Evidence List", "headers": ["#", "Evidence Ref", "SHA-256 Hash", "Platform", "Capture Date", "Description"], "rows": [] },
      { "type": "table", "title": "Timeline of Events", "headers": ["Date/Time", "Event", "Source", "Remarks"], "rows": [] },
      { "type": "keyValue", "title": "Legal Provisions", "entries": [] },
      { "type": "text", "title": "Findings & Analysis", "content": "{{findings}}" },
      { "type": "text", "title": "Conclusion", "content": "{{conclusion}}" },
      { "type": "text", "title": "Officer Declaration", "content": "I, {{officer_name}} (Badge: {{officer_badge}}), hereby declare that the contents of this report are true to the best of my knowledge and that all digital evidence referenced herein has been preserved in accordance with ISO 27037 standards.\n\nSignature: ____________________\nDate: {{declaration_date}}" }
    ],
    "footer": { "text": "CONFIDENTIAL — For Court Use Only", "confidentiality": "This document contains sensitive law enforcement information. Unauthorized disclosure is prohibited.", "pageNumbers": true }
  }'::jsonb,
  '{
    "placeholders": [
      { "name": "case_number", "type": "string", "required": true },
      { "name": "case_title", "type": "string", "required": true },
      { "name": "officer_name", "type": "string", "required": true },
      { "name": "officer_badge", "type": "string", "required": true },
      { "name": "report_date", "type": "date", "required": true },
      { "name": "district", "type": "string", "required": false },
      { "name": "executive_summary", "type": "string", "required": true },
      { "name": "findings", "type": "string", "required": true },
      { "name": "conclusion", "type": "string", "required": true },
      { "name": "declaration_date", "type": "date", "required": true }
    ]
  }'::jsonb,
  true
)
ON CONFLICT DO NOTHING;

-- 2. Alert Analysis Report — threat assessment and platform breakdown
INSERT INTO report_template (name, template_type, content_jsonb, content_schema, is_active)
VALUES (
  'Alert Analysis Report',
  'INTELLIGENCE',
  '{
    "header": { "title": "Alert Analysis Report", "subtitle": "Threat Assessment & Platform Intelligence" },
    "sections": [
      { "type": "keyValue", "title": "Report Overview", "entries": [
        { "label": "Report Reference", "value": "{{report_ref}}" },
        { "label": "Analyst", "value": "{{analyst_name}}" },
        { "label": "Period Covered", "value": "{{period_from}} to {{period_to}}" },
        { "label": "Report Date", "value": "{{report_date}}" }
      ]},
      { "type": "text", "title": "Threat Assessment Summary", "content": "{{threat_summary}}" },
      { "type": "table", "title": "Alert Summary by Priority", "headers": ["Priority", "Count", "Actioned", "Pending", "Avg Response Time"], "rows": [] },
      { "type": "table", "title": "Platform Breakdown", "headers": ["Platform", "Posts Monitored", "Alerts Generated", "Threat Score (Avg)", "Top Category"], "rows": [] },
      { "type": "text", "title": "Entity Analysis", "content": "{{entity_analysis}}" },
      { "type": "keyValue", "title": "Risk Scoring Methodology", "entries": [
        { "label": "Classification Model", "value": "{{model_name}}" },
        { "label": "Confidence Threshold", "value": "{{confidence_threshold}}" },
        { "label": "Alert Threshold", "value": "{{alert_threshold}}" }
      ]},
      { "type": "text", "title": "Recommendations", "content": "{{recommendations}}" }
    ],
    "footer": { "text": "Generated by TEF Social Media Monitoring System", "confidentiality": "RESTRICTED — Internal Use Only", "pageNumbers": true }
  }'::jsonb,
  '{
    "placeholders": [
      { "name": "report_ref", "type": "string", "required": true },
      { "name": "analyst_name", "type": "string", "required": true },
      { "name": "period_from", "type": "date", "required": true },
      { "name": "period_to", "type": "date", "required": true },
      { "name": "report_date", "type": "date", "required": true },
      { "name": "threat_summary", "type": "string", "required": true },
      { "name": "entity_analysis", "type": "string", "required": false },
      { "name": "model_name", "type": "string", "required": false },
      { "name": "confidence_threshold", "type": "number", "required": false },
      { "name": "alert_threshold", "type": "number", "required": false },
      { "name": "recommendations", "type": "string", "required": false }
    ]
  }'::jsonb,
  true
)
ON CONFLICT DO NOTHING;

-- 3. Section 65B Certificate — IT Act compliance certificate for digital evidence
INSERT INTO report_template (name, template_type, content_jsonb, content_schema, is_active)
VALUES (
  'Section 65B Certificate',
  'COURT_EXPORT',
  '{
    "header": { "title": "Certificate under Section 65B", "subtitle": "Indian Evidence Act, 1872 (as amended by IT Act, 2000)" },
    "sections": [
      { "type": "text", "title": "", "content": "Certificate issued under Section 65B(4) of the Indian Evidence Act, 1872, for the admissibility of electronic records as evidence." },
      { "type": "keyValue", "title": "Case Details", "entries": [
        { "label": "Case Number", "value": "{{case_number}}" },
        { "label": "Court", "value": "{{court_name}}" },
        { "label": "FIR Number", "value": "{{fir_number}}" }
      ]},
      { "type": "keyValue", "title": "Electronic Record Details", "entries": [
        { "label": "Evidence Reference", "value": "{{evidence_ref}}" },
        { "label": "Nature of Record", "value": "{{record_nature}}" },
        { "label": "Source Platform", "value": "{{source_platform}}" },
        { "label": "Source URL", "value": "{{source_url}}" },
        { "label": "Date of Capture", "value": "{{capture_date}}" },
        { "label": "Capture Tool", "value": "{{capture_tool}}" }
      ]},
      { "type": "keyValue", "title": "Hash Verification", "entries": [
        { "label": "Hash Algorithm", "value": "SHA-256" },
        { "label": "Hash Value", "value": "{{evidence_hash}}" },
        { "label": "Verification Status", "value": "{{verification_status}}" },
        { "label": "Verification Date", "value": "{{verification_date}}" }
      ]},
      { "type": "text", "title": "Certificate Statement", "content": "I, {{certifier_name}} ({{certifier_designation}}), holding the position of {{certifier_position}} at {{certifier_organization}}, hereby certify that:\n\n1. The electronic record described above was produced by a computer during the period over which the computer was used regularly to store or process information for the purposes of any activities regularly carried on over that period by the person having lawful control over the use of the computer.\n\n2. During the said period, information of the kind contained in the electronic record was regularly fed into the computer in the ordinary course of the said activities.\n\n3. Throughout the material part of the said period, the computer was operating properly, and if not, any respect in which it was not operating properly was not such as to affect the electronic record or the accuracy of its contents.\n\n4. The information contained in the electronic record reproduces or is derived from such information fed into the computer in the ordinary course of the said activities.\n\n5. The hash value (SHA-256: {{evidence_hash}}) has been verified and matches the original capture, confirming the integrity of the electronic record." },
      { "type": "keyValue", "title": "Certifier Details", "entries": [
        { "label": "Name", "value": "{{certifier_name}}" },
        { "label": "Designation", "value": "{{certifier_designation}}" },
        { "label": "Organization", "value": "{{certifier_organization}}" },
        { "label": "Date", "value": "{{certificate_date}}" }
      ]},
      { "type": "text", "title": "", "content": "Signature: ____________________\n\nSeal:" }
    ],
    "footer": { "text": "This certificate is issued under Section 65B(4) of the Indian Evidence Act, 1872", "confidentiality": "COURT DOCUMENT — Handle as per court directives", "pageNumbers": true }
  }'::jsonb,
  '{
    "placeholders": [
      { "name": "case_number", "type": "string", "required": true },
      { "name": "court_name", "type": "string", "required": true },
      { "name": "fir_number", "type": "string", "required": false },
      { "name": "evidence_ref", "type": "string", "required": true },
      { "name": "record_nature", "type": "string", "required": true },
      { "name": "source_platform", "type": "string", "required": true },
      { "name": "source_url", "type": "string", "required": false },
      { "name": "capture_date", "type": "date", "required": true },
      { "name": "capture_tool", "type": "string", "required": true },
      { "name": "evidence_hash", "type": "string", "required": true },
      { "name": "verification_status", "type": "string", "required": true },
      { "name": "verification_date", "type": "date", "required": true },
      { "name": "certifier_name", "type": "string", "required": true },
      { "name": "certifier_designation", "type": "string", "required": true },
      { "name": "certifier_position", "type": "string", "required": true },
      { "name": "certifier_organization", "type": "string", "required": true },
      { "name": "certificate_date", "type": "date", "required": true }
    ]
  }'::jsonb,
  true
)
ON CONFLICT DO NOTHING;
