#!/usr/bin/env bash
###############################################################################
# Pipeline driver generated by the plan-to-pipeline skill.
#
# - Runs one phase per fresh Codex session.
# - Verifies each phase's exit_criteria outside the model.
# - gate:auto advances on GREEN.
# - gate:human parks until approvals/<id>.approved exists.
# - Resumable: done phases are skipped.
# - Hard-stops on RED with no retry loop.
# - Safe by default: dry-run unless --execute and not on main/master.
#
# Layout, relative to this script:
#   phases.yaml  prompts/  checks/  .state/  approvals/  logs/
#
# Paths inside phases.yaml are relative to the git repo root.
#
# Usage:
#   ./run.sh
#   ./run.sh --status
#   ./run.sh --execute
#   ./run.sh --from <ID>
#   ./run.sh --reset <ID>
#
# Env:
#   CODEX_BIN    default: codex
#   CODEX_FLAGS  default: --sandbox workspace-write
#   CODEX_MODEL  optional model name
#   NOTIFY_CMD   optional command called with a park/failure message
###############################################################################
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(git -C "$HERE" rev-parse --show-toplevel 2>/dev/null || echo "$HERE")"
MANIFEST="$HERE/phases.yaml"
STATE="$HERE/.state"
APPROVALS="$HERE/approvals"
LOGS="$HERE/logs"
mkdir -p "$STATE" "$APPROVALS" "$LOGS"
cd "$ROOT" || exit 2

CODEX_BIN="${CODEX_BIN:-codex}"
CODEX_FLAGS="${CODEX_FLAGS:---sandbox workspace-write}"
# shellcheck disable=SC2206
CODEX_EXTRA_FLAGS=( $CODEX_FLAGS )
CODEX_MODEL_ARGS=()
[ -n "${CODEX_MODEL:-}" ] && CODEX_MODEL_ARGS=(--model "$CODEX_MODEL")
TIMEOUT_BIN="$(command -v timeout || command -v gtimeout || true)"

EXECUTE=0
STATUS=0
FROM=""
RESET=""

while [ $# -gt 0 ]; do
  case "$1" in
    --execute) EXECUTE=1 ;;
    --status) STATUS=1 ;;
    --from) FROM="$2"; shift ;;
    --reset) RESET="$2"; shift ;;
    -h|--help) sed -n '2,36p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1"; exit 2 ;;
  esac
  shift
done

notify() {
  echo ">> $*"
  [ -n "${NOTIFY_CMD:-}" ] && "$NOTIFY_CMD" "$*" || true
}

state_of() {
  cat "$STATE/$1.status" 2>/dev/null || echo pending
}

set_state() {
  echo "$2" > "$STATE/$1.status"
}

approved() {
  [ -f "$APPROVALS/$1.approved" ]
}

if [ -n "$RESET" ]; then
  rm -f "$STATE/$RESET.status"
  echo "reset $RESET"
  exit 0
fi

read_phases() {
  ruby -ryaml - "$MANIFEST" <<'RB'
manifest = YAML.load_file(ARGV.fetch(0))
Array(manifest["phases"]).each do |phase|
  row = [
    phase.fetch("id"),
    phase["name"].to_s,
    phase.fetch("prompt"),
    (phase["exit_criteria"] || "true").to_s,
    (phase["gate"] || "human").to_s,
    Array(phase["depends_on"]).join(",")
  ]
  puts row.join("\t")
end
RB
}

PHASE_TIMEOUT="$(
  ruby -ryaml - "$MANIFEST" <<'RB'
manifest = YAML.load_file(ARGV.fetch(0))
puts((manifest["defaults"] || {})["phase_timeout_seconds"] || 3600)
RB
)"

if [ "$STATUS" = 1 ]; then
  echo "== pipeline state =="
  while IFS=$'\t' read -r id name prompt exit_cmd gate deps; do
    printf "  %-10s %-18s %s\n" "$id" "[$(state_of "$id")]" "$name"
  done < <(read_phases)
  exit 0
fi

branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
if [ "$EXECUTE" = 1 ]; then
  if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
    echo "REFUSING to --execute on '$branch'. Create a sandbox branch first."
    echo "Example: git checkout -b pipeline-run"
    exit 3
  fi
  echo "== EXECUTE on branch '$branch' | agent: $CODEX_BIN exec ${CODEX_FLAGS} | timeout ${PHASE_TIMEOUT}s (${TIMEOUT_BIN:-none}) =="
else
  echo "== DRY-RUN. Pass --execute on a sandbox branch to run for real. Branch: '$branch' =="
fi

started=0
while IFS=$'\t' read -r id name prompt exit_cmd gate deps; do
  if [ -n "$FROM" ] && [ "$started" = 0 ]; then
    if [ "$id" = "$FROM" ]; then
      started=1
    else
      echo "  skip $id (before --from $FROM)"
      continue
    fi
  fi

  st="$(state_of "$id")"
  if [ "$st" = done ]; then
    echo "  ok $id done - skip"
    continue
  fi

  if [ "$st" = awaiting-approval ]; then
    if approved "$id"; then
      set_state "$id" done
      echo "  ok $id approved - done"
      continue
    fi
    notify "PARKED at human gate: $id ($name). Approve with: touch $APPROVALS/$id.approved"
    exit 0
  fi

  for dep in $(echo "$deps" | tr ',' ' '); do
    if [ -n "$dep" ] && [ "$(state_of "$dep")" != done ]; then
      echo "  blocked $id on $dep ($(state_of "$dep"))"
      exit 0
    fi
  done

  echo ""
  echo "-- $id : $name --"
  echo "   prompt: $prompt"
  echo "   verify: $exit_cmd"
  echo "   gate:   $gate"

  if [ "$EXECUTE" = 0 ]; then
    echo "   [dry-run] would run a fresh Codex session, then verify."
    echo "   Preview of exit_criteria:"
    ( eval "$exit_cmd" ) 2>&1 | sed 's/^/     /' || true
    echo "   stop: dry-run shows the next actionable phase only."
    exit 0
  fi

  if [ ! -s "$prompt" ]; then
    echo "missing prompt file: $prompt"
    exit 2
  fi

  set_state "$id" running
  snap="$(git rev-parse --short HEAD 2>/dev/null || echo '?')"
  log="$LOGS/${id}-$(date +%Y%m%d-%H%M%S 2>/dev/null || echo run).log"
  echo "   git snapshot: $snap"
  echo "   rollback line: git reset --hard $snap"
  echo "   running fresh Codex session -> $log"

  codex_cmd=("$CODEX_BIN" exec -C "$ROOT")
  [ "${#CODEX_MODEL_ARGS[@]}" -gt 0 ] && codex_cmd+=("${CODEX_MODEL_ARGS[@]}")
  [ "${#CODEX_EXTRA_FLAGS[@]}" -gt 0 ] && codex_cmd+=("${CODEX_EXTRA_FLAGS[@]}")
  codex_cmd+=(-)

  if [ -n "$TIMEOUT_BIN" ]; then
    "$TIMEOUT_BIN" "$PHASE_TIMEOUT" "${codex_cmd[@]}" < "$prompt" 2>&1 | tee "$log"
  else
    echo "   no timeout binary found; install coreutils for gtimeout on macOS"
    "${codex_cmd[@]}" < "$prompt" 2>&1 | tee "$log"
  fi

  echo "   verifying exit_criteria outside Codex..."
  if eval "$exit_cmd"; then
    if [ "$gate" = auto ]; then
      set_state "$id" done
      echo "   GREEN + gate:auto - advancing"
      continue
    fi
    set_state "$id" awaiting-approval
    notify "GREEN - $id ($name) passed checks; PARKED at human gate. Review, then touch $APPROVALS/$id.approved and re-run."
    exit 0
  fi

  set_state "$id" failed
  notify "RED - $id ($name) failed exit_criteria. HARD STOP. Log: $log. Fix then re-run, or use --reset $id."
  exit 1
done < <(read_phases)

echo ""
echo "all phases done."
