import { FastifyInstance } from "fastify";
import { query } from "../db";
import { sendError, send404 } from "../errors";
import { executeTransition } from "../workflow-bridge";
import { getAvailableTransitions } from "../workflow-bridge/transitions";
import { createPdfGenerator, createDocxGenerator } from "@puda/api-integrations";
import { generateAndLogWatermark } from "../services/watermark";

function buildReportTemplate(report: Record<string, any>) {
  const content = report.content_jsonb || {};
  const sections: Array<{ type: "text" | "table" | "keyValue"; title?: string; content?: string; entries?: Array<{ label: string; value: string }>; headers?: string[]; rows?: string[][] }> = [];

  sections.push({
    type: "keyValue" as const,
    title: "Report Details",
    entries: [
      { label: "Report ID", value: report.report_id },
      { label: "Reference", value: report.report_ref || "N/A" },
      { label: "State", value: report.state_id },
      { label: "Created By", value: report.created_by },
      { label: "Created At", value: String(report.created_at) },
    ],
  });

  if (content.summary) {
    sections.push({ type: "text" as const, title: "Summary", content: content.summary });
  }
  if (content.alerts && Array.isArray(content.alerts)) {
    sections.push({
      type: "table" as const,
      title: "Alerts",
      headers: ["#", "Alert", "Priority", "Status"],
      rows: content.alerts.map((a: any, i: number) => [String(i + 1), a.title || String(a), a.priority || "N/A", a.state_id || "N/A"]),
    });
  }
  if (content.conclusion) {
    sections.push({ type: "text" as const, title: "Conclusion", content: content.conclusion });
  }

  const knownKeys = new Set(["summary", "alerts", "conclusion"]);
  const extraKeys = Object.keys(content).filter((k) => !knownKeys.has(k));
  if (extraKeys.length > 0) {
    const extra = Object.fromEntries(extraKeys.map((k) => [k, content[k]]));
    sections.push({ type: "text" as const, title: "Additional Data", content: JSON.stringify(extra, null, 2) });
  }

  return {
    header: {
      title: report.title,
      subtitle: `Social Media Intelligence Report — ${report.report_ref || report.report_id}`,
      department: "Technology-Enabled Forensic Lab",
      generatedAt: new Date().toISOString(),
      generatedBy: report.created_by,
      referenceNumber: report.report_ref,
    },
    sections,
    footer: {
      text: "Generated by TEF Social Media Monitoring System",
      confidentiality: "CONFIDENTIAL — For authorized personnel only",
      pageNumbers: true,
    },
    watermark: report.state_id === "DRAFT" ? "DRAFT" : undefined,
  };
}

export async function registerReportRoutes(app: FastifyInstance): Promise<void> {
  app.get("/api/v1/reports", async (request, reply) => {
    try {
      const { state_id, limit: rawLimit, offset: rawOffset } = request.query as Record<string, string | undefined>;
      const unitId = request.authUser?.unitId || null;
      const limit = Math.min(Math.max(parseInt(rawLimit || "50", 10) || 50, 1), 200);
      const offset = Math.max(parseInt(rawOffset || "0", 10) || 0, 0);
      const result = await query(
        `SELECT report_id, report_ref, case_id, template_id, title, state_id, created_by, created_at,
                COUNT(*) OVER() AS total_count
         FROM report_instance
         WHERE ($1::text IS NULL OR state_id = $1)
           AND (unit_id = $2::uuid)
         ORDER BY created_at DESC
         LIMIT $3 OFFSET $4`,
        [state_id || null, unitId, limit, offset],
      );
      const total = result.rows.length > 0 ? parseInt(result.rows[0].total_count, 10) : 0;
      return { reports: result.rows.map(({ total_count, ...r }: any) => r), total };
    } catch (err: unknown) {
      request.log.error(err, "Failed to list reports");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  app.post("/api/v1/reports", {
    schema: { body: { type: "object", additionalProperties: false, required: ["caseId", "title"], properties: { caseId: { type: "string", format: "uuid" }, title: { type: "string" }, templateId: { type: "string" } } } },
  }, async (request, reply) => {
    try {
      const { caseId, title, templateId } = request.body as { caseId: string; title: string; templateId?: string };
      const { userId } = request.authUser!;
      const unitId = request.authUser?.unitId || null;

      const caseCheck = await query(`SELECT 1 FROM case_record WHERE case_id = $1`, [caseId]);
      if (caseCheck.rows.length === 0) {
        return send404(reply, "CASE_NOT_FOUND", "Case not found");
      }

      const refResult = await query(`SELECT 'TEF-RPT-' || EXTRACT(YEAR FROM NOW())::text || '-' || LPAD(nextval('sm_report_ref_seq')::text, 6, '0') AS ref`);
      const reportRef = refResult.rows[0].ref;
      const result = await query(
        `INSERT INTO report_instance (case_id, title, template_id, created_by, unit_id, report_ref) VALUES ($1, $2, $3, $4, $5, $6)
         RETURNING report_id, report_ref, case_id, title, state_id, created_by, created_at`,
        [caseId, title, templateId || null, userId, unitId, reportRef],
      );
      reply.code(201);
      return { report: result.rows[0] };
    } catch (err: unknown) {
      request.log.error(err, "Failed to create report");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  app.get("/api/v1/reports/:id", {
    schema: { params: { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const result = await query(
        `SELECT report_id, report_ref, case_id, template_id, title, content_jsonb, state_id, row_version,
                created_by, approved_by, exported_at, created_at, updated_at
         FROM report_instance WHERE report_id = $1`,
        [id],
      );
      if (result.rows.length === 0) {
        return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      }
      return { report: result.rows[0] };
    } catch (err: unknown) {
      request.log.error(err, "Failed to get report");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  app.get("/api/v1/reports/:id/transitions", {
    schema: { params: { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const result = await query(`SELECT state_id FROM report_instance WHERE report_id = $1`, [id]);
      if (result.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      return { transitions: getAvailableTransitions("sm_report", result.rows[0].state_id) };
    } catch (err: unknown) {
      request.log.error(err, "Failed to get report transitions");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // Export report as PDF/DOCX using shared generators (FR-08 AC-05: requires APPROVED state)
  app.post("/api/v1/reports/:id/export", {
    schema: {
      params: { type: "object", required: ["id"], properties: { id: { type: "string", format: "uuid" } } },
      querystring: { type: "object", additionalProperties: false, properties: { format: { type: "string", enum: ["pdf", "docx"], default: "pdf" } } },
    },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const qs = request.query as { format?: string };
      const format = qs.format || "pdf";

      const result = await query(
        `SELECT report_id, report_ref, title, content_jsonb, state_id, approved_by, created_by, created_at FROM report_instance WHERE report_id = $1`,
        [id],
      );
      if (result.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      const report = result.rows[0];

      // Export approval gate: report must be APPROVED (or PUBLISHED) and have an approver
      if (report.state_id === "DRAFT" || report.state_id === "PENDING_REVIEW") {
        return sendError(reply, 403, "EXPORT_NOT_APPROVED", "Report must be approved before export");
      }
      if (!report.approved_by) {
        return sendError(reply, 403, "EXPORT_NOT_APPROVED", "Report must have an approver before export");
      }
      // FR-17: Generate watermark for exported report
      const { userId } = request.authUser!;
      const watermarkText = await generateAndLogWatermark(userId, "sm_report", id, `REPORT_EXPORT_${format.toUpperCase()}`);

      // Set watermark on the template
      const template = buildReportTemplate(report);
      template.watermark = watermarkText;

      // Record export timestamp
      await query(
        `UPDATE report_instance SET exported_at = NOW(), updated_at = NOW() WHERE report_id = $1`,
        [id],
      );

      if (format === "docx") {
        const docxGen = createDocxGenerator();
        const buffer = await docxGen.generate(template);
        reply.header("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
        reply.header("Content-Disposition", `attachment; filename="report-${id}.docx"`);
        reply.header("X-Watermark", watermarkText);
        return reply.send(buffer);
      }

      const pdfGen = createPdfGenerator();
      const buffer = await pdfGen.generate(template);
      reply.header("Content-Type", "application/pdf");
      reply.header("Content-Disposition", `attachment; filename="report-${id}.pdf"`);
      reply.header("X-Watermark", watermarkText);
      return reply.send(buffer);
    } catch (err: unknown) {
      request.log.error(err, "Failed to export report");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // Dedicated PDF endpoint — FR-17: requires approval before export
  app.get("/api/v1/reports/:id/pdf", {
    schema: { params: { type: "object", required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const result = await query(
        `SELECT report_id, report_ref, title, content_jsonb, state_id, approved_by, created_by, created_at FROM report_instance WHERE report_id = $1`,
        [id],
      );
      if (result.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      const report = result.rows[0];

      // FR-17: Export approval gate
      if (!report.approved_by) {
        return sendError(reply, 403, "EXPORT_NOT_APPROVED", "Report must be approved before export");
      }

      const { userId } = request.authUser!;
      const watermarkText = await generateAndLogWatermark(userId, "sm_report", id, "REPORT_EXPORT_PDF");

      const template = buildReportTemplate(report);
      template.watermark = watermarkText;

      await query(`UPDATE report_instance SET exported_at = NOW(), updated_at = NOW() WHERE report_id = $1`, [id]);

      const pdfGen = createPdfGenerator();
      const buffer = await pdfGen.generate(template);
      reply.header("Content-Type", "application/pdf");
      reply.header("Content-Disposition", `attachment; filename="report-${id}.pdf"`);
      reply.header("X-Watermark", watermarkText);
      return reply.send(buffer);
    } catch (err: unknown) {
      request.log.error(err, "Failed to generate PDF");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // Dedicated DOCX endpoint — FR-17: requires approval before export
  app.get("/api/v1/reports/:id/docx", {
    schema: { params: { type: "object", required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const result = await query(
        `SELECT report_id, report_ref, title, content_jsonb, state_id, approved_by, created_by, created_at FROM report_instance WHERE report_id = $1`,
        [id],
      );
      if (result.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      const report = result.rows[0];

      // FR-17: Export approval gate
      if (!report.approved_by) {
        return sendError(reply, 403, "EXPORT_NOT_APPROVED", "Report must be approved before export");
      }

      const { userId } = request.authUser!;
      const watermarkText = await generateAndLogWatermark(userId, "sm_report", id, "REPORT_EXPORT_DOCX");

      const template = buildReportTemplate(report);
      template.watermark = watermarkText;

      await query(`UPDATE report_instance SET exported_at = NOW(), updated_at = NOW() WHERE report_id = $1`, [id]);

      const docxGen = createDocxGenerator();
      const buffer = await docxGen.generate(template);
      reply.header("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
      reply.header("Content-Disposition", `attachment; filename="report-${id}.docx"`);
      reply.header("X-Watermark", watermarkText);
      return reply.send(buffer);
    } catch (err: unknown) {
      request.log.error(err, "Failed to generate DOCX");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  app.post("/api/v1/reports/:id/transition", {
    schema: {
      params: { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string", format: "uuid" } } },
      body: { type: "object", additionalProperties: false, required: ["transitionId"], properties: { transitionId: { type: "string" }, remarks: { type: "string" } } },
    },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const { transitionId, remarks } = request.body as { transitionId: string; remarks?: string };
      const { userId, roles } = request.authUser!;

      const result = await executeTransition(
        id, "sm_report", transitionId, userId, "OFFICER", roles, remarks,
      );
      if (!result.success) {
        return sendError(reply, 409, result.error || "TRANSITION_FAILED", "Report transition failed");
      }
      return { success: true, newStateId: result.newStateId };
    } catch (err: unknown) {
      request.log.error(err, "Failed to execute report transition");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });
}
