import { FastifyInstance } from "fastify";
import { query } from "../db";
import { sendError, send404 } from "../errors";
import { createRoleGuard } from "@puda/api-core";
import { executeTransition } from "../workflow-bridge";
import { getAvailableTransitions } from "../workflow-bridge/transitions";
import { createPdfGenerator, createDocxGenerator } from "@puda/api-integrations";
import type { ReportTemplate } from "@puda/api-integrations";
import { generateAndLogWatermark } from "../services/watermark";
import { interpolateTemplate } from "../services/template-interpolator";
import { getMappings } from "../services/legal-mapper";

const requireSupervisor = createRoleGuard(["SUPERVISOR", "PLATFORM_ADMINISTRATOR"]);

function buildReportTemplate(report: Record<string, any>) {
  const content = report.content_jsonb || {};
  const sections: Array<{ type: "text" | "table" | "keyValue"; title?: string; content?: string; entries?: Array<{ label: string; value: string }>; headers?: string[]; rows?: string[][] }> = [];

  sections.push({
    type: "keyValue" as const,
    title: "Report Details",
    entries: [
      { label: "Report ID", value: report.report_id },
      { label: "Reference", value: report.report_ref || "N/A" },
      { label: "State", value: report.state_id },
      { label: "Created By", value: report.created_by },
      { label: "Created At", value: String(report.created_at) },
    ],
  });

  if (content.summary) {
    sections.push({ type: "text" as const, title: "Summary", content: content.summary });
  }
  if (content.alerts && Array.isArray(content.alerts)) {
    sections.push({
      type: "table" as const,
      title: "Alerts",
      headers: ["#", "Alert", "Priority", "Status"],
      rows: content.alerts.map((a: any, i: number) => [String(i + 1), a.title || String(a), a.priority || "N/A", a.state_id || "N/A"]),
    });
  }
  if (content.conclusion) {
    sections.push({ type: "text" as const, title: "Conclusion", content: content.conclusion });
  }

  if (content.legal_provisions && Array.isArray(content.legal_provisions)) {
    sections.push({
      type: "table" as const,
      title: "Applicable Legal Provisions",
      headers: ["Act", "Section", "Offence", "Max Penalty", "Confidence"],
      rows: content.legal_provisions.map((lp: any) => [
        lp.act_name || "N/A",
        lp.section || "N/A",
        lp.description || "N/A",
        lp.penalty_summary || "N/A",
        lp.confidence != null ? `${lp.confidence}%` : "N/A",
      ]),
    });
  }

  const knownKeys = new Set(["summary", "alerts", "conclusion", "legal_provisions", "findings", "methodology", "recommendations", "evidence_items", "timeline"]);
  const extraKeys = Object.keys(content).filter((k) => !knownKeys.has(k));
  if (extraKeys.length > 0) {
    const extra = Object.fromEntries(extraKeys.map((k) => [k, content[k]]));
    sections.push({ type: "text" as const, title: "Additional Data", content: JSON.stringify(extra, null, 2) });
  }

  return {
    header: {
      title: report.title,
      subtitle: `Social Media Intelligence Report — ${report.report_ref || report.report_id}`,
      department: "Technology-Enabled Forensic Lab",
      generatedAt: new Date().toISOString(),
      generatedBy: report.created_by,
      referenceNumber: report.report_ref,
    },
    sections,
    footer: {
      text: "Generated by TEF Social Media Monitoring System",
      confidentiality: "CONFIDENTIAL — For authorized personnel only",
      pageNumbers: true,
    },
    watermark: report.state_id === "DRAFT" ? "DRAFT" : undefined,
  };
}

export async function registerReportRoutes(app: FastifyInstance): Promise<void> {
  app.get("/api/v1/reports", async (request, reply) => {
    try {
      const { state_id, limit: rawLimit, offset: rawOffset } = request.query as Record<string, string | undefined>;
      const unitId = request.authUser?.unitId || null;
      const limit = Math.min(Math.max(parseInt(rawLimit || "50", 10) || 50, 1), 200);
      const offset = Math.max(parseInt(rawOffset || "0", 10) || 0, 0);
      const result = await query(
        `SELECT report_id, report_ref, case_id, template_id, title, state_id, created_by, created_at,
                COUNT(*) OVER() AS total_count
         FROM report_instance
         WHERE ($1::text IS NULL OR state_id = $1)
           AND (unit_id = $2::uuid)
         ORDER BY created_at DESC
         LIMIT $3 OFFSET $4`,
        [state_id || null, unitId, limit, offset],
      );
      const total = result.rows.length > 0 ? parseInt(result.rows[0].total_count, 10) : 0;
      return { reports: result.rows.map(({ total_count, ...r }: any) => r), total };
    } catch (err: unknown) {
      request.log.error(err, "Failed to list reports");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  app.post("/api/v1/reports", {
    schema: { body: { type: "object", additionalProperties: false, required: ["caseId", "title"], properties: { caseId: { type: "string", format: "uuid" }, title: { type: "string" }, templateId: { type: "string" } } } },
  }, async (request, reply) => {
    try {
      const { caseId, title, templateId } = request.body as { caseId: string; title: string; templateId?: string };
      const { userId } = request.authUser!;
      const unitId = request.authUser?.unitId || null;

      const caseCheck = await query(`SELECT 1 FROM case_record WHERE case_id = $1`, [caseId]);
      if (caseCheck.rows.length === 0) {
        return send404(reply, "CASE_NOT_FOUND", "Case not found");
      }

      const refResult = await query(`SELECT 'TEF-RPT-' || EXTRACT(YEAR FROM NOW())::text || '-' || LPAD(nextval('sm_report_ref_seq')::text, 6, '0') AS ref`);
      const reportRef = refResult.rows[0].ref;
      const result = await query(
        `INSERT INTO report_instance (case_id, title, template_id, created_by, unit_id, report_ref) VALUES ($1, $2, $3, $4, $5, $6)
         RETURNING report_id, report_ref, case_id, title, state_id, created_by, created_at`,
        [caseId, title, templateId || null, userId, unitId, reportRef],
      );
      reply.code(201);
      return { report: result.rows[0] };
    } catch (err: unknown) {
      request.log.error(err, "Failed to create report");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  app.get("/api/v1/reports/:id", {
    schema: { params: { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const result = await query(
        `SELECT report_id, report_ref, case_id, template_id, title, content_jsonb, state_id, row_version,
                created_by, approved_by, exported_at, created_at, updated_at
         FROM report_instance WHERE report_id = $1`,
        [id],
      );
      if (result.rows.length === 0) {
        return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      }
      return { report: result.rows[0] };
    } catch (err: unknown) {
      request.log.error(err, "Failed to get report");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // PATCH /reports/:id — update report content (DRAFT state only)
  app.patch("/api/v1/reports/:id", {
    schema: {
      params: { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string", format: "uuid" } } },
      body: { type: "object", additionalProperties: false, properties: { content_jsonb: { type: "object" }, title: { type: "string" } } },
    },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const { content_jsonb, title } = request.body as { content_jsonb?: Record<string, unknown>; title?: string };
      const { userId } = request.authUser!;

      const existing = await query(`SELECT state_id, template_id FROM report_instance WHERE report_id = $1`, [id]);
      if (existing.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      if (existing.rows[0].state_id !== "DRAFT") {
        return sendError(reply, 409, "NOT_DRAFT", "Only DRAFT reports can be edited");
      }

      const updates: string[] = [];
      const params: unknown[] = [];
      let paramIdx = 1;

      if (content_jsonb !== undefined) {
        updates.push(`content_jsonb = $${paramIdx++}`);
        params.push(JSON.stringify(content_jsonb));
      }
      if (title !== undefined) {
        updates.push(`title = $${paramIdx++}`);
        params.push(title);
      }
      if (updates.length === 0) {
        return sendError(reply, 400, "NO_CHANGES", "No fields to update");
      }
      updates.push(`updated_at = NOW()`);
      params.push(id);

      const result = await query(
        `UPDATE report_instance SET ${updates.join(", ")} WHERE report_id = $${paramIdx}
         RETURNING report_id, report_ref, title, content_jsonb, state_id, updated_at`,
        params,
      );

      // Audit log
      await query(
        `INSERT INTO audit_log (user_id, action, entity_type, entity_id, details)
         VALUES ($1, 'REPORT_CONTENT_UPDATED', 'report_instance', $2, $3)`,
        [userId, id, JSON.stringify({ fields: Object.keys(request.body as Record<string, unknown>) })],
      ).catch(() => {});

      return { report: result.rows[0] };
    } catch (err: unknown) {
      request.log.error(err, "Failed to update report");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // POST /reports/:id/populate — auto-populate report content from linked case data
  app.post("/api/v1/reports/:id/populate", {
    schema: { params: { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };

      const reportRes = await query(
        `SELECT report_id, case_id, template_id, state_id, content_jsonb, created_by, report_ref
         FROM report_instance WHERE report_id = $1`,
        [id],
      );
      if (reportRes.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      const report = reportRes.rows[0];

      if (report.state_id !== "DRAFT") {
        return sendError(reply, 409, "NOT_DRAFT", "Only DRAFT reports can be populated");
      }

      const caseId = report.case_id;
      const content: Record<string, unknown> = report.content_jsonb || {};

      // Gather evidence items linked to the case
      const evidenceRes = await query(
        `SELECT evidence_id, evidence_ref, hash_sha256, capture_timestamp, source_platform, source_url, description
         FROM evidence_item WHERE case_id = $1 ORDER BY capture_timestamp DESC`,
        [caseId],
      );
      if (evidenceRes.rows.length > 0) {
        content.evidence_items = evidenceRes.rows.map((e: any) => ({
          evidence_ref: e.evidence_ref || e.evidence_id,
          hash_sha256: e.hash_sha256 || "N/A",
          platform: e.source_platform || "N/A",
          capture_date: e.capture_timestamp ? new Date(e.capture_timestamp).toISOString().split("T")[0] : "N/A",
          source_url: e.source_url || "",
          description: e.description || "",
        }));
      }

      // Gather alerts linked to the case
      const alertRes = await query(
        `SELECT alert_id, title, priority, state_id, created_at
         FROM sm_alert WHERE case_id = $1 ORDER BY created_at DESC`,
        [caseId],
      );
      if (alertRes.rows.length > 0) {
        content.alerts = alertRes.rows.map((a: any) => ({
          title: a.title,
          priority: a.priority,
          state_id: a.state_id,
        }));
      }

      // Gather legal entity mappings for the case
      const legalRes = await query(
        `SELECT lm.confidence, lm.mapping_source, lm.confirmed,
                sl.act_name, sl.section, sl.description, sl.penalty_summary
         FROM legal_mapping lm
         JOIN statute_library sl ON sl.statute_id = lm.statute_id
         WHERE lm.entity_type = 'case_record' AND lm.entity_id = $1
         ORDER BY lm.confidence DESC`,
        [caseId],
      );
      if (legalRes.rows.length > 0) {
        content.legal_provisions = legalRes.rows;
      }

      // Gather timeline from content items
      const timelineRes = await query(
        `SELECT content_id, platform, content_text, threat_score, published_at
         FROM content_item WHERE content_id IN (
           SELECT content_id FROM sm_alert WHERE case_id = $1
         ) ORDER BY published_at ASC`,
        [caseId],
      );
      if (timelineRes.rows.length > 0) {
        content.timeline = timelineRes.rows.map((c: any) => ({
          date: c.published_at ? new Date(c.published_at).toISOString() : "N/A",
          platform: c.platform,
          snippet: (c.content_text || "").slice(0, 200),
          threat_score: c.threat_score,
        }));
      }

      // If template_id is set, try to interpolate template placeholders
      if (report.template_id) {
        const tmplRes = await query(
          `SELECT content_jsonb FROM report_template WHERE template_id = $1`,
          [report.template_id],
        );
        if (tmplRes.rows.length > 0 && tmplRes.rows[0].content_jsonb) {
          const tmplContent = tmplRes.rows[0].content_jsonb;
          // Build variables from gathered data
          const vars: Record<string, string> = {
            case_number: caseId,
            case_title: content.summary as string || "",
            report_ref: report.report_ref || "",
            report_date: new Date().toISOString().split("T")[0],
            officer_name: report.created_by || "",
          };
          try {
            const interpolated = interpolateTemplate(tmplContent as ReportTemplate, vars);
            content._template_interpolated = interpolated;
          } catch { /* template interpolation is best-effort */ }
        }
      }

      await query(
        `UPDATE report_instance SET content_jsonb = $1, updated_at = NOW() WHERE report_id = $2`,
        [JSON.stringify(content), id],
      );

      return { report: { report_id: id, content_jsonb: content }, populated: true };
    } catch (err: unknown) {
      request.log.error(err, "Failed to populate report");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // GET /reports/:id/legal-mappings — legal provisions linked to the report's case
  app.get("/api/v1/reports/:id/legal-mappings", {
    schema: { params: { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const reportRes = await query(`SELECT case_id FROM report_instance WHERE report_id = $1`, [id]);
      if (reportRes.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      const mappings = await getMappings("case_record", reportRes.rows[0].case_id);
      return { mappings };
    } catch (err: unknown) {
      request.log.error(err, "Failed to get legal mappings");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // report-template routes are in report-template.routes.ts

  app.get("/api/v1/reports/:id/transitions", {
    schema: { params: { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const result = await query(`SELECT state_id FROM report_instance WHERE report_id = $1`, [id]);
      if (result.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      return { transitions: getAvailableTransitions("sm_report", result.rows[0].state_id) };
    } catch (err: unknown) {
      request.log.error(err, "Failed to get report transitions");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // Export report as PDF/DOCX using shared generators (FR-08 AC-05: requires APPROVED state)
  app.post("/api/v1/reports/:id/export", {
    schema: {
      params: { type: "object", required: ["id"], properties: { id: { type: "string", format: "uuid" } } },
      querystring: { type: "object", additionalProperties: false, properties: { format: { type: "string", enum: ["pdf", "docx"], default: "pdf" } } },
    },
  }, async (request, reply) => {
    if (!requireSupervisor(request, reply)) return;
    try {
      const { id } = request.params as { id: string };
      const qs = request.query as { format?: string };
      const format = qs.format || "pdf";

      const result = await query(
        `SELECT report_id, report_ref, title, content_jsonb, state_id, approved_by, created_by, created_at FROM report_instance WHERE report_id = $1`,
        [id],
      );
      if (result.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      const report = result.rows[0];

      // Export approval gate: report must be APPROVED (or PUBLISHED) and have an approver
      if (report.state_id === "DRAFT" || report.state_id === "PENDING_REVIEW") {
        return sendError(reply, 403, "EXPORT_NOT_APPROVED", "Report must be approved before export");
      }
      if (!report.approved_by) {
        return sendError(reply, 403, "EXPORT_NOT_APPROVED", "Report must have an approver before export");
      }
      // FR-17: Generate watermark for exported report
      const { userId } = request.authUser!;
      const watermarkText = await generateAndLogWatermark(userId, "sm_report", id, `REPORT_EXPORT_${format.toUpperCase()}`);

      // Template-driven export: if report has a template_id, use its structure
      let template: ReportTemplate & { watermark?: string };
      if (report.template_id) {
        const tmplRes = await query(`SELECT content_jsonb FROM report_template WHERE template_id = $1`, [report.template_id]);
        if (tmplRes.rows.length > 0 && tmplRes.rows[0].content_jsonb) {
          const tmplContent = tmplRes.rows[0].content_jsonb as ReportTemplate;
          const vars: Record<string, string> = {
            report_ref: report.report_ref || "",
            report_date: new Date().toISOString().split("T")[0],
            officer_name: report.created_by || "",
          };
          // Merge any content_jsonb string fields as template variables
          const content = report.content_jsonb || {};
          for (const [k, v] of Object.entries(content)) {
            if (typeof v === "string") vars[k] = v;
          }
          template = interpolateTemplate(tmplContent, vars);
          // Add populated data sections from content_jsonb
          const fallback = buildReportTemplate(report);
          for (const sec of fallback.sections) {
            if (sec.title && !template.sections.some((s) => s.title === sec.title)) {
              template.sections.push(sec);
            }
          }
        } else {
          template = buildReportTemplate(report);
        }
      } else {
        template = buildReportTemplate(report);
      }
      template.watermark = watermarkText;

      // Record export timestamp
      await query(
        `UPDATE report_instance SET exported_at = NOW(), updated_at = NOW() WHERE report_id = $1`,
        [id],
      );

      if (format === "docx") {
        const docxGen = createDocxGenerator();
        const buffer = await docxGen.generate(template);
        reply.header("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
        reply.header("Content-Disposition", `attachment; filename="report-${id}.docx"`);
        reply.header("X-Watermark", watermarkText);
        return reply.send(buffer);
      }

      const pdfGen = createPdfGenerator();
      const buffer = await pdfGen.generate(template);
      reply.header("Content-Type", "application/pdf");
      reply.header("Content-Disposition", `attachment; filename="report-${id}.pdf"`);
      reply.header("X-Watermark", watermarkText);
      return reply.send(buffer);
    } catch (err: unknown) {
      request.log.error(err, "Failed to export report");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // Dedicated PDF endpoint — FR-17: requires approval before export
  app.get("/api/v1/reports/:id/pdf", {
    schema: { params: { type: "object", required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    if (!requireSupervisor(request, reply)) return;
    try {
      const { id } = request.params as { id: string };
      const result = await query(
        `SELECT report_id, report_ref, title, content_jsonb, state_id, approved_by, created_by, created_at FROM report_instance WHERE report_id = $1`,
        [id],
      );
      if (result.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      const report = result.rows[0];

      // FR-17: Export approval gate
      if (!report.approved_by) {
        return sendError(reply, 403, "EXPORT_NOT_APPROVED", "Report must be approved before export");
      }

      const { userId } = request.authUser!;
      const watermarkText = await generateAndLogWatermark(userId, "sm_report", id, "REPORT_EXPORT_PDF");

      const template = buildReportTemplate(report);
      template.watermark = watermarkText;

      await query(`UPDATE report_instance SET exported_at = NOW(), updated_at = NOW() WHERE report_id = $1`, [id]);

      const pdfGen = createPdfGenerator();
      const buffer = await pdfGen.generate(template);
      reply.header("Content-Type", "application/pdf");
      reply.header("Content-Disposition", `attachment; filename="report-${id}.pdf"`);
      reply.header("X-Watermark", watermarkText);
      return reply.send(buffer);
    } catch (err: unknown) {
      request.log.error(err, "Failed to generate PDF");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // Dedicated DOCX endpoint — FR-17: requires approval before export
  app.get("/api/v1/reports/:id/docx", {
    schema: { params: { type: "object", required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    if (!requireSupervisor(request, reply)) return;
    try {
      const { id } = request.params as { id: string };
      const result = await query(
        `SELECT report_id, report_ref, title, content_jsonb, state_id, approved_by, created_by, created_at FROM report_instance WHERE report_id = $1`,
        [id],
      );
      if (result.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      const report = result.rows[0];

      // FR-17: Export approval gate
      if (!report.approved_by) {
        return sendError(reply, 403, "EXPORT_NOT_APPROVED", "Report must be approved before export");
      }

      const { userId } = request.authUser!;
      const watermarkText = await generateAndLogWatermark(userId, "sm_report", id, "REPORT_EXPORT_DOCX");

      const template = buildReportTemplate(report);
      template.watermark = watermarkText;

      await query(`UPDATE report_instance SET exported_at = NOW(), updated_at = NOW() WHERE report_id = $1`, [id]);

      const docxGen = createDocxGenerator();
      const buffer = await docxGen.generate(template);
      reply.header("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
      reply.header("Content-Disposition", `attachment; filename="report-${id}.docx"`);
      reply.header("X-Watermark", watermarkText);
      return reply.send(buffer);
    } catch (err: unknown) {
      request.log.error(err, "Failed to generate DOCX");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  app.post("/api/v1/reports/:id/transition", {
    schema: {
      params: { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string", format: "uuid" } } },
      body: { type: "object", additionalProperties: false, required: ["transitionId"], properties: { transitionId: { type: "string" }, remarks: { type: "string" } } },
    },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const { transitionId, remarks } = request.body as { transitionId: string; remarks?: string };
      const { userId, roles } = request.authUser!;

      // FR-08 AC-05: Four-eyes check — approver must differ from report creator
      const reportData = await query(`SELECT created_by, state_id FROM report_instance WHERE report_id = $1`, [id]);
      if (reportData.rows.length === 0) {
        return sendError(reply, 404, "REPORT_NOT_FOUND", "Report not found");
      }
      const availableTransitions = getAvailableTransitions("sm_report", reportData.rows[0].state_id);
      const targetTransition = availableTransitions.find((t: any) => t.transitionId === transitionId);
      if (targetTransition?.toStateId === "APPROVED") {
        if (reportData.rows[0].created_by === userId) {
          return sendError(reply, 403, "FOUR_EYES_VIOLATION", "Report creator cannot approve their own report");
        }
        // Set approved_by
        await query(`UPDATE report_instance SET approved_by = $1, updated_at = NOW() WHERE report_id = $2`, [userId, id]);
      }

      const result = await executeTransition(
        id, "sm_report", transitionId, userId, "OFFICER", roles, remarks,
      );
      if (!result.success) {
        return sendError(reply, 409, result.error || "TRANSITION_FAILED", "Report transition failed");
      }
      return { success: true, newStateId: result.newStateId };
    } catch (err: unknown) {
      request.log.error(err, "Failed to execute report transition");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });
}
