/**
 * L2: Shared constants for state IDs, role IDs, event types.
 * Single source of truth — import from @puda/shared/constants.
 */

export const ApplicationState = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  PENDING_AT_CLERK: "PENDING_AT_CLERK",
  PENDING_AT_SR_ASSISTANT_ACCOUNTS: "PENDING_AT_SR_ASSISTANT_ACCOUNTS",
  PENDING_AT_ACCOUNT_OFFICER: "PENDING_AT_ACCOUNT_OFFICER",
  PENDING_AT_JUNIOR_ENGINEER: "PENDING_AT_JUNIOR_ENGINEER",
  PENDING_AT_SDO: "PENDING_AT_SDO",
  PENDING_AT_DRAFTSMAN: "PENDING_AT_DRAFTSMAN",
  QUERY_PENDING: "QUERY_PENDING",
  RESUBMITTED: "RESUBMITTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CLOSED: "CLOSED",
} as const;

export const TaskStatus = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
} as const;

export const SystemRole = {
  CLERK: "CLERK",
  SR_ASST: "PUDA_SR_ASST",
  ACCOUNT_OFFICER: "PUDA_ACCOUNT_OFFICER",
  JUNIOR_ENGINEER: "JUNIOR_ENGINEER",
  SDO: "SDO",
  DRAFTSMAN: "DRAFTSMAN",
  ESTATE_OFFICER: "ESTATE_OFFICER",
  SUPERINTENDENT: "SUPERINTENDENT",
} as const;

export const UserType = {
  CITIZEN: "CITIZEN",
  OFFICER: "OFFICER",
  ADMIN: "ADMIN",
} as const;

export const NotificationEvent = {
  APPLICATION_SUBMITTED: "APPLICATION_SUBMITTED",
  QUERY_RAISED: "QUERY_RAISED",
  QUERY_RESPONDED: "QUERY_RESPONDED",
  APPLICATION_APPROVED: "APPLICATION_APPROVED",
  APPLICATION_REJECTED: "APPLICATION_REJECTED",
  OUTPUT_ISSUED: "OUTPUT_ISSUED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  SLA_BREACH: "SLA_BREACH",
} as const;

export const ActionType = {
  FORWARD: "FORWARD",
  QUERY: "QUERY",
  APPROVE: "APPROVE",
  REJECT: "REJECT",
} as const;
