/**
 * Notice Letter DAL — formal notices and letters dispatched to applicants.
 *
 * A notice_letter represents a formal communication generated by the system
 * (or an officer) and dispatched electronically or physically. Types include:
 * QUERY, DEFICIENCY, APPROVAL, REJECTION, DEMAND_LETTER, OTHER.
 *
 * Notices link to:
 *   - A query (for QUERY-type notices)
 *   - A decision (for APPROVAL/REJECTION notices)
 *   - A signed artifact (generated PDF stored via StorageAdapter)
 */
import { query } from "./db";
import { v4 as uuidv4 } from "uuid";
import type { PoolClient } from "pg";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type NoticeType = "QUERY" | "DEFICIENCY" | "APPROVAL" | "REJECTION" | "DEMAND_LETTER" | "OTHER";
export type DispatchMode = "ELECTRONIC" | "PHYSICAL";

export interface NoticeLetter {
  notice_id: string;
  arn: string;
  notice_type: NoticeType;
  template_code: string | null;
  subject: string | null;
  body_text: string | null;
  generated_at: Date;
  dispatch_mode: DispatchMode | null;
  dispatch_address_jsonb: Record<string, unknown>;
  dispatched_at: Date | null;
  signed_artifact_key: string | null;
  qr_token: string | null;
  query_id: string | null;
  decision_id: string | null;
  issued_by_user_id: string | null;
  issued_by_role: string | null;
  metadata_jsonb: Record<string, unknown>;
  created_at: Date;
}

export interface CreateNoticeInput {
  arn: string;
  noticeType: NoticeType;
  templateCode?: string;
  subject?: string;
  bodyText?: string;
  dispatchMode?: DispatchMode;
  dispatchAddress?: Record<string, unknown>;
  signedArtifactKey?: string;
  qrToken?: string;
  queryId?: string;
  decisionId?: string;
  issuedByUserId?: string;
  issuedByRole?: string;
  metadata?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// CRUD
// ---------------------------------------------------------------------------

/** Create a new notice letter. */
export async function createNoticeLetter(
  input: CreateNoticeInput,
  client?: PoolClient
): Promise<NoticeLetter> {
  const run = client
    ? (text: string, params?: unknown[]) => client.query(text, params)
    : query;

  const id = uuidv4();
  await run(
    `INSERT INTO notice_letter
       (notice_id, arn, notice_type, template_code,
        subject, body_text, dispatch_mode, dispatch_address_jsonb,
        signed_artifact_key, qr_token,
        query_id, decision_id,
        issued_by_user_id, issued_by_role, metadata_jsonb)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)`,
    [
      id,
      input.arn,
      input.noticeType,
      input.templateCode || null,
      input.subject || null,
      input.bodyText || null,
      input.dispatchMode || null,
      JSON.stringify(input.dispatchAddress || {}),
      input.signedArtifactKey || null,
      input.qrToken || null,
      input.queryId || null,
      input.decisionId || null,
      input.issuedByUserId || null,
      input.issuedByRole || null,
      JSON.stringify(input.metadata || {}),
    ]
  );

  return (await getNoticeById(id, client))!;
}

/** Mark a notice as dispatched. */
export async function markDispatched(
  noticeId: string,
  dispatchMode?: DispatchMode
): Promise<NoticeLetter | null> {
  await query(
    `UPDATE notice_letter SET
       dispatched_at = NOW(),
       dispatch_mode = COALESCE($2, dispatch_mode)
     WHERE notice_id = $1 AND dispatched_at IS NULL`,
    [noticeId, dispatchMode || null]
  );
  return getNoticeById(noticeId);
}

/** Attach a signed artifact (PDF) to a notice. */
export async function attachArtifact(
  noticeId: string,
  storageKey: string,
  qrToken?: string
): Promise<NoticeLetter | null> {
  await query(
    `UPDATE notice_letter SET
       signed_artifact_key = $2,
       qr_token = COALESCE($3, qr_token)
     WHERE notice_id = $1`,
    [noticeId, storageKey, qrToken || null]
  );
  return getNoticeById(noticeId);
}

// ---------------------------------------------------------------------------
// Read
// ---------------------------------------------------------------------------

export async function getNoticeById(
  noticeId: string,
  client?: PoolClient
): Promise<NoticeLetter | null> {
  const run = client
    ? (text: string, params?: unknown[]) => client.query(text, params)
    : query;
  const result = await run(
    "SELECT * FROM notice_letter WHERE notice_id = $1",
    [noticeId]
  );
  return result.rows.length > 0 ? rowToNotice(result.rows[0]) : null;
}

/** Get all notices for an application. */
export async function getNoticesForApplication(
  arn: string,
  noticeType?: NoticeType
): Promise<NoticeLetter[]> {
  const typeFilter = noticeType ? " AND notice_type = $2" : "";
  const params: unknown[] = [arn];
  if (noticeType) params.push(noticeType);

  const result = await query(
    `SELECT * FROM notice_letter WHERE arn = $1${typeFilter} ORDER BY generated_at DESC`,
    params
  );
  return result.rows.map(rowToNotice);
}

/** Get the notice linked to a specific query. */
export async function getNoticeForQuery(queryId: string): Promise<NoticeLetter | null> {
  const result = await query(
    "SELECT * FROM notice_letter WHERE query_id = $1 LIMIT 1",
    [queryId]
  );
  return result.rows.length > 0 ? rowToNotice(result.rows[0]) : null;
}

/** Get notices linked to a specific decision. */
export async function getNoticesForDecision(decisionId: string): Promise<NoticeLetter[]> {
  const result = await query(
    "SELECT * FROM notice_letter WHERE decision_id = $1 ORDER BY generated_at DESC",
    [decisionId]
  );
  return result.rows.map(rowToNotice);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function rowToNotice(row: any): NoticeLetter {
  return {
    notice_id: row.notice_id,
    arn: row.arn,
    notice_type: row.notice_type as NoticeType,
    template_code: row.template_code,
    subject: row.subject,
    body_text: row.body_text,
    generated_at: row.generated_at,
    dispatch_mode: row.dispatch_mode as DispatchMode | null,
    dispatch_address_jsonb: row.dispatch_address_jsonb || {},
    dispatched_at: row.dispatched_at,
    signed_artifact_key: row.signed_artifact_key,
    qr_token: row.qr_token,
    query_id: row.query_id,
    decision_id: row.decision_id,
    issued_by_user_id: row.issued_by_user_id,
    issued_by_role: row.issued_by_role,
    metadata_jsonb: row.metadata_jsonb || {},
    created_at: row.created_at,
  };
}
