import { FastifyInstance } from "fastify";
import { query } from "../db";
import { sendError, send404 } from "../errors";
import { executeTransition } from "../workflow-bridge";
import { getAvailableTransitions } from "../workflow-bridge/transitions";
import { createPdfGenerator, createDocxGenerator } from "@puda/api-integrations";
import { createRoleGuard } from "@puda/api-core";

const requireReportPublish = createRoleGuard(["SUPERVISOR", "ADMINISTRATOR", "PLATFORM_ADMINISTRATOR"]);

function buildReportTemplate(report: Record<string, any>) {
  const content = report.content_jsonb || {};
  const sections: Array<{ type: "text" | "table" | "keyValue"; title?: string; content?: string; entries?: Array<{ label: string; value: string }>; headers?: string[]; rows?: string[][] }> = [];

  sections.push({
    type: "keyValue" as const,
    title: "Report Details",
    entries: [
      { label: "Report ID", value: report.report_id },
      { label: "Reference", value: report.report_ref || "N/A" },
      { label: "Type", value: report.report_type || "N/A" },
      { label: "State", value: report.state_id },
      { label: "Created By", value: report.created_by },
      { label: "Created At", value: String(report.created_at) },
    ],
  });

  if (content.summary) {
    sections.push({ type: "text" as const, title: "Summary", content: content.summary });
  }
  if (content.findings && Array.isArray(content.findings)) {
    sections.push({
      type: "table" as const,
      title: "Findings",
      headers: ["#", "Finding", "Severity"],
      rows: content.findings.map((f: any, i: number) => [String(i + 1), f.description || String(f), f.severity || "N/A"]),
    });
  }
  if (content.conclusion) {
    sections.push({ type: "text" as const, title: "Conclusion", content: content.conclusion });
  }

  // Fallback: dump remaining content as text
  const knownKeys = new Set(["summary", "findings", "conclusion"]);
  const extraKeys = Object.keys(content).filter((k) => !knownKeys.has(k));
  if (extraKeys.length > 0) {
    const extra = Object.fromEntries(extraKeys.map((k) => [k, content[k]]));
    sections.push({ type: "text" as const, title: "Additional Data", content: JSON.stringify(extra, null, 2) });
  }

  return {
    header: {
      title: report.title,
      subtitle: `Forensic Report — ${report.report_ref || report.report_id}`,
      department: "E-Forensic Lab",
      generatedAt: new Date().toISOString(),
      generatedBy: report.created_by,
      referenceNumber: report.report_ref,
    },
    sections,
    footer: {
      text: "Generated by E-Forensic Lab Management System",
      confidentiality: "CONFIDENTIAL — For authorized personnel only",
      pageNumbers: true,
    },
    watermark: report.state_id === "DRAFT" ? "DRAFT" : undefined,
  };
}

function applyRedaction(text: string, rules: Array<{ pattern: string; replacement: string }>): string {
  let result = text;
  for (const rule of rules) {
    try {
      const regex = new RegExp(rule.pattern, "gi");
      result = result.replace(regex, rule.replacement || "[REDACTED]");
    } catch {
      // Invalid regex — skip this rule
    }
  }
  return result;
}

function redactTemplate(template: ReturnType<typeof buildReportTemplate>, rules: Array<{ pattern: string; replacement: string }>) {
  for (const section of template.sections) {
    if (section.content) {
      section.content = applyRedaction(section.content, rules);
    }
    if (section.entries) {
      for (const entry of section.entries) {
        entry.value = applyRedaction(entry.value, rules);
      }
    }
    if (section.rows) {
      section.rows = section.rows.map((row) => row.map((cell) => applyRedaction(cell, rules)));
    }
  }
  return template;
}

export async function registerReportRoutes(app: FastifyInstance): Promise<void> {
  // Redaction profile CRUD
  app.get("/api/v1/redaction-profiles", async (request) => {
    const result = await query(
      `SELECT profile_id, profile_name, rules, is_active, created_by, created_at FROM redaction_profile WHERE is_active = TRUE ORDER BY profile_name`,
    );
    return { profiles: result.rows };
  });

  app.post("/api/v1/redaction-profiles", {
    schema: {
      body: {
        type: "object",
        additionalProperties: false,
        required: ["profileName", "rules"],
        properties: {
          profileName: { type: "string" },
          rules: { type: "array", items: { type: "object", required: ["pattern", "replacement"], properties: { pattern: { type: "string" }, replacement: { type: "string" } } } },
        },
      },
    },
  }, async (request, reply) => {
    const { profileName, rules } = request.body as { profileName: string; rules: Array<{ pattern: string; replacement: string }> };
    const { userId } = request.authUser!;
    const result = await query(
      `INSERT INTO redaction_profile (profile_name, rules, created_by) VALUES ($1, $2, $3)
       RETURNING profile_id, profile_name, rules, is_active, created_at`,
      [profileName, JSON.stringify(rules), userId],
    );
    reply.code(201);
    return { profile: result.rows[0] };
  });

  app.delete("/api/v1/redaction-profiles/:profileId", {
    schema: { params: { type: "object", required: ["profileId"], properties: { profileId: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    const { profileId } = request.params as { profileId: string };
    const result = await query(`UPDATE redaction_profile SET is_active = FALSE WHERE profile_id = $1 RETURNING profile_id`, [profileId]);
    if (result.rows.length === 0) return send404(reply, "PROFILE_NOT_FOUND", "Redaction profile not found");
    return { success: true };
  });
  app.get("/api/v1/cases/:caseId/reports", {
    schema: {
      params: { type: "object", additionalProperties: false, required: ["caseId"], properties: { caseId: { type: "string", format: "uuid" } } },
      querystring: {
        type: "object",
        additionalProperties: false,
        properties: {
          state_id: { type: "string", maxLength: 100 },
          limit: { type: "integer", minimum: 1, maximum: 200, default: 50 },
          offset: { type: "integer", minimum: 0, default: 0 },
        },
      },
    },
  }, async (request, reply) => {
    try {
      const { caseId } = request.params as { caseId: string };
      const { state_id, limit: rawLimit, offset: rawOffset } = request.query as Record<string, string | undefined>;
      const limit = Math.min(Math.max(parseInt(rawLimit || "50", 10) || 50, 1), 200);
      const offset = Math.max(parseInt(rawOffset || "0", 10) || 0, 0);

      const result = await query(
        `SELECT report_id, case_id, title, report_type, report_ref, state_id, version_number,
                created_by, approved_by, published_at, created_at,
                COUNT(*) OVER() AS total_count
         FROM report
         WHERE case_id = $1
           AND ($2::text IS NULL OR state_id = $2)
         ORDER BY created_at DESC
         LIMIT $3 OFFSET $4`,
        [caseId, state_id || null, limit, offset],
      );
      const total = result.rows.length > 0 ? parseInt(result.rows[0].total_count, 10) : 0;
      return { reports: result.rows.map(({ total_count, ...r }: any) => r), total };
    } catch (err: unknown) {
      request.log.error(err, "Failed to list reports");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  app.post("/api/v1/reports", {
    schema: { body: { type: "object", additionalProperties: false, required: ["caseId", "title"], properties: { caseId: { type: "string", format: "uuid" }, title: { type: "string" }, templateId: { type: "string" } } } },
  }, async (request, reply) => {
    try {
      const { caseId, title, templateId } = request.body as { caseId: string; title: string; templateId?: string };
      const { userId } = request.authUser!;

      const caseCheck = await query(`SELECT 1 FROM forensic_case WHERE case_id = $1`, [caseId]);
      if (caseCheck.rows.length === 0) {
        return send404(reply, "CASE_NOT_FOUND", "Case not found");
      }

      const refResult = await query(`SELECT 'EF-RPT-' || EXTRACT(YEAR FROM NOW())::text || '-' || LPAD(nextval('forensic_report_ref_seq')::text, 6, '0') AS ref`);
      const reportRef = refResult.rows[0].ref;
      const result = await query(
        `INSERT INTO report (case_id, title, template_id, report_ref, created_by) VALUES ($1, $2, $3, $4, $5)
         RETURNING report_id, case_id, title, report_type, template_id, report_ref, state_id, version_number, created_by, created_at`,
        [caseId, title, templateId || null, reportRef, userId],
      );
      reply.code(201);
      return { report: result.rows[0] };
    } catch (err: unknown) {
      request.log.error(err, "Failed to create report");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // Export report as PDF/DOCX with optional redaction profile
  app.post("/api/v1/reports/:id/export", {
    schema: {
      params: { type: "object", required: ["id"], properties: { id: { type: "string", format: "uuid" } } },
      querystring: { type: "object", additionalProperties: false, properties: {
        format: { type: "string", enum: ["pdf", "docx"], default: "pdf" },
        redactionProfileId: { type: "string", format: "uuid" },
      } },
    },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const qs = request.query as { format?: string; redactionProfileId?: string };
      const format = qs.format || "pdf";

      const result = await query(
        `SELECT report_id, title, report_type, report_ref, content_jsonb, state_id, created_by, created_at FROM report WHERE report_id = $1`,
        [id],
      );
      if (result.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      const report = result.rows[0];
      let template = buildReportTemplate(report);

      // Apply redaction profile if specified
      if (qs.redactionProfileId) {
        const profileResult = await query(
          `SELECT rules FROM redaction_profile WHERE profile_id = $1 AND is_active = TRUE`,
          [qs.redactionProfileId],
        );
        if (profileResult.rows.length > 0) {
          const rules = typeof profileResult.rows[0].rules === "string"
            ? JSON.parse(profileResult.rows[0].rules)
            : profileResult.rows[0].rules;
          template = redactTemplate(template, rules);
        }
      }

      if (format === "docx") {
        const docxGen = createDocxGenerator();
        const buffer = await docxGen.generate(template);
        reply.header("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
        reply.header("Content-Disposition", `attachment; filename="report-${id}.docx"`);
        return reply.send(buffer);
      }

      const pdfGen = createPdfGenerator();
      const buffer = await pdfGen.generate(template);
      reply.header("Content-Type", "application/pdf");
      reply.header("Content-Disposition", `attachment; filename="report-${id}.pdf"`);
      return reply.send(buffer);
    } catch (err: unknown) {
      request.log.error(err, "Failed to export report");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // Dedicated PDF endpoint
  app.get("/api/v1/reports/:id/pdf", {
    schema: { params: { type: "object", required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const result = await query(
        `SELECT report_id, title, report_type, report_ref, content_jsonb, state_id, created_by, created_at FROM report WHERE report_id = $1`,
        [id],
      );
      if (result.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      const template = buildReportTemplate(result.rows[0]);
      const pdfGen = createPdfGenerator();
      const buffer = await pdfGen.generate(template);
      reply.header("Content-Type", "application/pdf");
      reply.header("Content-Disposition", `attachment; filename="report-${id}.pdf"`);
      return reply.send(buffer);
    } catch (err: unknown) {
      request.log.error(err, "Failed to generate PDF");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  // Dedicated DOCX endpoint
  app.get("/api/v1/reports/:id/docx", {
    schema: { params: { type: "object", required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const result = await query(
        `SELECT report_id, title, report_type, report_ref, content_jsonb, state_id, created_by, created_at FROM report WHERE report_id = $1`,
        [id],
      );
      if (result.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      const template = buildReportTemplate(result.rows[0]);
      const docxGen = createDocxGenerator();
      const buffer = await docxGen.generate(template);
      reply.header("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
      reply.header("Content-Disposition", `attachment; filename="report-${id}.docx"`);
      return reply.send(buffer);
    } catch (err: unknown) {
      request.log.error(err, "Failed to generate DOCX");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  app.get("/api/v1/reports/:id/transitions", {
    schema: { params: { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string", format: "uuid" } } } },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const result = await query(`SELECT state_id FROM report WHERE report_id = $1`, [id]);
      if (result.rows.length === 0) return send404(reply, "REPORT_NOT_FOUND", "Report not found");
      return { transitions: getAvailableTransitions("forensic_report", result.rows[0].state_id) };
    } catch (err: unknown) {
      request.log.error(err, "Failed to get report transitions");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });

  app.post("/api/v1/reports/:id/transition", {
    schema: {
      params: { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string", format: "uuid" } } },
      body: { type: "object", additionalProperties: false, required: ["transitionId"], properties: { transitionId: { type: "string" }, remarks: { type: "string" } } },
    },
  }, async (request, reply) => {
    try {
      const { id } = request.params as { id: string };
      const { transitionId, remarks } = request.body as { transitionId: string; remarks?: string };
      const { userId, roles } = request.authUser!;

      // Business logic checks use best-effort state read; transition validation is atomic in engine
      const target = getAvailableTransitions("forensic_report",
        (await query(`SELECT state_id FROM report WHERE report_id = $1`, [id])).rows[0]?.state_id ?? "",
      ).find((t) => t.transitionId === transitionId);

      // Role guard: only SUPERVISOR / ADMINISTRATOR may publish
      if (target?.toStateId === "PUBLISHED") {
        if (!requireReportPublish(request, reply)) return;

        // FR-11 AC-04: Block publish when findings are unreviewed
        // Fixed: use correct table name `ai_finding` instead of `finding`
        const unreviewedResult = await query(
          `SELECT COUNT(*) AS unreviewed_count FROM ai_finding WHERE case_id = (SELECT case_id FROM report WHERE report_id = $1) AND state_id = 'UNREVIEWED'`,
          [id],
        );
        if (parseInt(unreviewedResult.rows[0].unreviewed_count, 10) > 0) {
          return sendError(reply, 409, "UNREVIEWED_FINDINGS", "Cannot publish report with unreviewed findings");
        }
      }

      // FR-11 AC-03: Record approved_at on APPROVED transition
      if (target?.toStateId === "APPROVED") {
        await query(
          `UPDATE report SET approved_at = NOW(), approved_by = $1 WHERE report_id = $2`,
          [userId, id],
        );
      }

      const result = await executeTransition(
        id, "forensic_report", transitionId, userId, "OFFICER", roles, remarks,
      );
      if (!result.success) {
        if (result.error === "ENTITY_NOT_FOUND") return send404(reply, "REPORT_NOT_FOUND", "Report not found");
        return sendError(reply, 409, result.error || "TRANSITION_FAILED", "Report transition failed");
      }
      return { success: true, newStateId: result.newStateId };
    } catch (err: unknown) {
      request.log.error(err, "Failed to execute report transition");
      return sendError(reply, 500, "INTERNAL_ERROR", "An internal error occurred");
    }
  });
}
